// Comprehensive Mock Data Service
// Provides realistic mock data for flights, hotels, buses, trains, and cabs

const mockFlights = [
  {
    id: 'FL-001',
    airline: 'IndiGo',
    airlineCode: '6E',
    flightNumber: '6E-1234',
    departure: { city: 'Delhi (DEL)', time: '06:00', airport: 'Indira Gandhi International', terminal: '3' },
    arrival: { city: 'Mumbai (BOM)', time: '08:30', airport: 'Bombay', terminal: '2' },
    durationMinutes: 150,
    duration: '2h 30m',
    price: 3499,
    baseFare: 2800,
    taxes: 699,
    seatsAvailable: 45,
    totalSeats: 180,
    stops: 0,
    aircraft: 'A320',
    baggage: 15,
    cabin: 'Economy',
    cabinClass: 'Economy',
    isActive: true,
    rating: 4.5,
    reviews: 2342,
    amenities: ['WiFi', 'Meals', 'USB Charging']
  },
  {
    id: 'FL-002',
    airline: 'Air India',
    airlineCode: 'AI',
    flightNumber: 'AI-101',
    departure: { city: 'Delhi (DEL)', time: '08:15', airport: 'Indira Gandhi International', terminal: '1' },
    arrival: { city: 'Mumbai (BOM)', time: '10:45', airport: 'Bombay', terminal: '1' },
    durationMinutes: 150,
    duration: '2h 30m',
    price: 4299,
    baseFare: 3500,
    taxes: 799,
    seatsAvailable: 22,
    totalSeats: 250,
    stops: 0,
    aircraft: 'Boeing 777',
    baggage: 20,
    cabin: 'Business',
    cabinClass: 'Business',
    isActive: true,
    rating: 4.7,
    reviews: 3451,
    amenities: ['WiFi', 'Premium Meals', 'USB Charging', 'Extra Legroom', 'Priority Boarding']
  },
  {
    id: 'FL-003',
    airline: 'SpiceJet',
    airlineCode: 'SG',
    flightNumber: 'SG-8901',
    departure: { city: 'Delhi (DEL)', time: '10:30', airport: 'Indira Gandhi International', terminal: '2' },
    arrival: { city: 'Mumbai (BOM)', time: '13:00', airport: 'Bombay', terminal: '2' },
    durationMinutes: 150,
    duration: '2h 30m',
    price: 2799,
    baseFare: 2200,
    taxes: 599,
    seatsAvailable: 67,
    totalSeats: 180,
    stops: 0,
    aircraft: 'Boeing 737',
    baggage: 15,
    cabin: 'Economy',
    cabinClass: 'Economy',
    isActive: true,
    rating: 4.1,
    reviews: 1876,
    amenities: ['WiFi', 'Basic Snacks', 'USB Charging']
  },
  {
    id: 'FL-004',
    airline: 'Vistara',
    airlineCode: 'UK',
    flightNumber: 'UK-401',
    departure: { city: 'Delhi (DEL)', time: '14:45', airport: 'Indira Gandhi International', terminal: '3' },
    arrival: { city: 'Mumbai (BOM)', time: '17:15', airport: 'Bombay', terminal: '1' },
    durationMinutes: 150,
    duration: '2h 30m',
    price: 4599,
    baseFare: 3800,
    taxes: 799,
    seatsAvailable: 35,
    totalSeats: 200,
    stops: 0,
    aircraft: 'A320',
    baggage: 20,
    cabin: 'Premium Economy',
    cabinClass: 'Premium Economy',
    isActive: true,
    rating: 4.8,
    reviews: 2987,
    amenities: ['WiFi', 'Gourmet Meals', 'USB Charging', 'Priority Boarding', 'Extra Legroom']
  },
  {
    id: 'FL-005',
    airline: 'GoAir',
    airlineCode: 'G8',
    flightNumber: 'G8-502',
    departure: { city: 'Delhi (DEL)', time: '18:00', airport: 'Indira Gandhi International', terminal: '2' },
    arrival: { city: 'Mumbai (BOM)', time: '20:30', airport: 'Bombay', terminal: '2' },
    durationMinutes: 150,
    duration: '2h 30m',
    price: 3199,
    baseFare: 2500,
    taxes: 699,
    seatsAvailable: 52,
    totalSeats: 180,
    stops: 0,
    aircraft: 'Boeing 737',
    baggage: 15,
    cabin: 'Economy',
    cabinClass: 'Economy',
    isActive: true,
    rating: 4.3,
    reviews: 1654,
    amenities: ['WiFi', 'Meals', 'USB Charging']
  },
  {
    id: 'FL-006',
    airline: 'Air India Express',
    airlineCode: 'IX',
    flightNumber: 'IX-201',
    departure: { city: 'Delhi (DEL)', time: '22:00', airport: 'Indira Gandhi International', terminal: '1' },
    arrival: { city: 'Mumbai (BOM)', time: '00:30', airport: 'Bombay', terminal: '2' },
    durationMinutes: 150,
    duration: '2h 30m',
    price: 2599,
    baseFare: 2000,
    taxes: 599,
    seatsAvailable: 78,
    totalSeats: 180,
    stops: 0,
    aircraft: 'Boeing 737',
    baggage: 15,
    cabin: 'Economy',
    cabinClass: 'Economy',
    isActive: true,
    rating: 4.0,
    reviews: 1432,
    amenities: ['WiFi', 'Basic Snacks', 'USB Charging']
  },
  {
    id: 'FL-007',
    airline: 'IndiGo',
    airlineCode: '6E',
    flightNumber: '6E-5678',
    departure: { city: 'Bangalore (BLR)', time: '07:00', airport: 'Kempegowda International', terminal: '2' },
    arrival: { city: 'Delhi (DEL)', time: '09:15', airport: 'Indira Gandhi International', terminal: '3' },
    durationMinutes: 135,
    duration: '2h 15m',
    price: 3899,
    baseFare: 3100,
    taxes: 799,
    seatsAvailable: 40,
    totalSeats: 180,
    stops: 0,
    aircraft: 'A320',
    baggage: 15,
    cabin: 'Economy',
    cabinClass: 'Economy',
    isActive: true,
    rating: 4.5,
    reviews: 2156,
    amenities: ['WiFi', 'Meals', 'USB Charging']
  },
  {
    id: 'FL-008',
    airline: 'Air India',
    airlineCode: 'AI',
    flightNumber: 'AI-401',
    departure: { city: 'Bangalore (BLR)', time: '09:30', airport: 'Kempegowda International', terminal: '1' },
    arrival: { city: 'Delhi (DEL)', time: '11:45', airport: 'Indira Gandhi International', terminal: '1' },
    durationMinutes: 135,
    duration: '2h 15m',
    price: 4899,
    baseFare: 4000,
    taxes: 899,
    seatsAvailable: 28,
    totalSeats: 250,
    stops: 0,
    aircraft: 'Boeing 777',
    baggage: 20,
    cabin: 'Business',
    cabinClass: 'Business',
    isActive: true,
    rating: 4.7,
    reviews: 3234,
    amenities: ['WiFi', 'Premium Meals', 'USB Charging', 'Priority Boarding', 'Extra Legroom', 'Lounge Access']
  },
  {
    id: 'FL-009',
    airline: 'Vistara',
    airlineCode: 'UK',
    flightNumber: 'UK-231',
    departure: { city: 'Bangalore (BLR)', time: '13:00', airport: 'Kempegowda International', terminal: '2' },
    arrival: { city: 'Delhi (DEL)', time: '15:15', airport: 'Indira Gandhi International', terminal: '3' },
    durationMinutes: 135,
    duration: '2h 15m',
    price: 4299,
    baseFare: 3500,
    taxes: 799,
    seatsAvailable: 41,
    totalSeats: 200,
    stops: 0,
    aircraft: 'A320',
    baggage: 20,
    cabin: 'Premium Economy',
    cabinClass: 'Premium Economy',
    isActive: true,
    rating: 4.8,
    reviews: 2876,
    amenities: ['WiFi', 'Premium Meals', 'USB Charging', 'Priority Boarding', 'Extra Legroom']
  },
  {
    id: 'FL-010',
    airline: 'SpiceJet',
    airlineCode: 'SG',
    flightNumber: 'SG-321',
    departure: { city: 'Bangalore (BLR)', time: '15:30', airport: 'Kempegowda International', terminal: '1' },
    arrival: { city: 'Delhi (DEL)', time: '17:45', airport: 'Indira Gandhi International', terminal: '2' },
    durationMinutes: 135,
    duration: '2h 15m',
    price: 3299,
    baseFare: 2600,
    taxes: 699,
    seatsAvailable: 55,
    totalSeats: 180,
    stops: 0,
    aircraft: 'Boeing 737',
    baggage: 15,
    cabin: 'Economy',
    cabinClass: 'Economy',
    isActive: true,
    rating: 4.1,
    reviews: 1723,
    amenities: ['WiFi', 'Meals', 'USB Charging']
  }
]

const mockHotels = [
  {
    id: 'HT-001',
    name: 'The Oberoi New Delhi',
    city: 'Delhi',
    location: 'New Delhi, India',
    address: 'Dr. Zakir Hussain Marg, New Delhi 110003',
    rating: 4.8,
    reviews: 3245,
    price: 12500,
    roomsAvailable: 8,
    totalRooms: 220,
    roomType: '5 Star Luxury',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Spa', 'Fine Dining', '24/7 Concierge', 'Gym'],
    images: [
      'https://images.unsplash.com/photo-1631049307038-da31f703988f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584377860899-d2ae8d3e8d7e?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Luxury 5-star hotel with world-class amenities and exceptional service',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 2500,
    discount: 0,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 8,
    isActive: true
  },
  {
    id: 'HT-002',
    name: 'Radisson Blu Delhi',
    city: 'Delhi',
    location: 'Dwarka, New Delhi',
    address: 'NH-8, Dwarka, New Delhi 110077',
    rating: 4.5,
    reviews: 2156,
    price: 7999,
    roomsAvailable: 15,
    totalRooms: 400,
    roomType: '4 Star Premium',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Fitness Center', 'Restaurant', 'Business Center'],
    images: [
      'https://images.unsplash.com/photo-1578821868057-c31b76b80d73?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Premium 4-star hotel with modern facilities and comfortable rooms',
    cancellation: 'Free cancellation until 48 hours before checkin',
    taxes: 1600,
    discount: 800,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 15,
    isActive: true
  },
  {
    id: 'HT-003',
    name: 'ITC Maurya, a Luxury Collection Hotel',
    city: 'Delhi',
    location: 'Chanakya Puri, New Delhi',
    address: 'Chanakya Puri, New Delhi 110021',
    rating: 4.7,
    reviews: 2876,
    price: 11999,
    roomsAvailable: 5,
    totalRooms: 438,
    roomType: '5 Star Luxury',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Spa', 'Fine Dining', 'Business Center', 'Valet Parking'],
    images: [
      'https://images.unsplash.com/photo-1566669537602-b8f7b5ff87f9?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Luxurious heritage hotel with exceptional service and world-class amenities',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 2400,
    discount: 0,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 5,
    isActive: true
  },
  {
    id: 'HT-004',
    name: 'JW Marriott Mumbai Sahar',
    city: 'Mumbai',
    location: 'Andheri East, Mumbai',
    address: 'Airport Road, Andheri East, Mumbai 400099',
    rating: 4.6,
    reviews: 2543,
    price: 9999,
    roomsAvailable: 12,
    totalRooms: 380,
    roomType: '5 Star Luxury',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Fitness Center', 'Fine Dining', 'Business Center'],
    images: [
      'https://images.unsplash.com/photo-1595576142684-e58829a70f36?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Luxurious hotel with stunning views and premium amenities',
    cancellation: 'Free cancellation until 48 hours before checkin',
    taxes: 2000,
    discount: 500,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 12,
    isActive: true
  },
  {
    id: 'HT-005',
    name: 'Taj Hotel Mumbai',
    city: 'Mumbai',
    location: 'Colaba, Mumbai',
    address: 'Apollo Bunder, Colaba, Mumbai 400001',
    rating: 4.8,
    reviews: 3987,
    price: 14999,
    roomsAvailable: 3,
    totalRooms: 300,
    roomType: '5 Star Iconic',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Multiple Pools', 'Spa', 'Multiple Restaurants', 'Conference Center', 'Business Lounge'],
    images: [
      'https://images.unsplash.com/photo-1569305817188-a1ba3a0fde2c?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Iconic luxury hotel with legendary service and historic charm',
    cancellation: 'Flexible cancellation policy',
    taxes: 3000,
    discount: 1500,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 3,
    isActive: true
  },
  {
    id: 'HT-006',
    name: 'Hotel Holiday Inn Mumbai',
    city: 'Mumbai',
    location: 'Vile Parle, Mumbai',
    address: 'Vile Parle, Mumbai 400056',
    rating: 4.2,
    reviews: 1654,
    price: 5999,
    roomsAvailable: 20,
    totalRooms: 250,
    roomType: '3 Star Standard',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Fitness Center', 'Restaurant'],
    images: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Comfortable hotel with good amenities and convenient location',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 1200,
    discount: 600,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 20,
    isActive: true
  },
  {
    id: 'HT-007',
    name: 'The Leela Palace Bangalore',
    city: 'Bangalore',
    location: 'Koramangala, Bangalore',
    address: 'Koramangala, Bangalore 560034',
    rating: 4.7,
    reviews: 2341,
    price: 10999,
    roomsAvailable: 9,
    totalRooms: 350,
    roomType: '5 Star Luxury',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Spa', 'Fine Dining', 'Business Center', 'Golf Course Access'],
    images: [
      'https://images.unsplash.com/photo-1635558063341-0f4755adbc64?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Ultra-luxury hotel with exquisite design and world-class service',
    cancellation: 'Free cancellation until 48 hours before checkin',
    taxes: 2200,
    discount: 1100,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 9,
    isActive: true
  },
  {
    id: 'HT-008',
    name: 'Pullman Bangalore',
    city: 'Bangalore',
    location: 'Whitefield, Bangalore',
    address: 'Whitefield, Bangalore 560066',
    rating: 4.4,
    reviews: 1876,
    price: 6499,
    roomsAvailable: 18,
    totalRooms: 320,
    roomType: '4 Star Business',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Fitness Center', 'Business Center', 'Conference Rooms'],
    images: [
      'https://images.unsplash.com/photo-1564376264095-8d6e20a1c7f7?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Business-focused hotel with modern amenities and excellent connectivity',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 1300,
    discount: 650,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 18,
    isActive: true
  },
  {
    id: 'HT-009',
    name: 'Hyatt Centric Delhi',
    city: 'Delhi',
    location: 'Karol Bagh, Delhi',
    address: 'Karol Bagh, Delhi 110005',
    rating: 4.3,
    reviews: 1432,
    price: 5499,
    roomsAvailable: 25,
    totalRooms: 300,
    roomType: '4 Star Mid-Range',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Rooftop Bar', 'Fitness Center', 'Restaurant', 'Business Center'],
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b8d5?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Modern hotel with contemporary design and vibrant atmosphere',
    cancellation: 'Free cancellation until 48 hours before checkin',
    taxes: 1100,
    discount: 550,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 25,
    isActive: true
  },
  {
    id: 'HT-010',
    name: 'Three Star Hotel Mumbai',
    city: 'Mumbai',
    location: 'Bandra, Mumbai',
    address: 'Bandra, Mumbai 400050',
    rating: 3.9,
    reviews: 987,
    price: 4999,
    roomsAvailable: 30,
    totalRooms: 200,
    roomType: '3 Star Budget',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Restaurant', 'Fitness Center'],
    images: [
      'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Affordable hotel with essential amenities in trendy location',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 1000,
    discount: 500,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 30,
    isActive: true
  },
  {
    id: 'HT-011',
    name: 'The Leela Palace Udaipur',
    city: 'Udaipur',
    location: 'Lake Pichola, Udaipur',
    address: 'Lake Pichola, Udaipur 313001',
    rating: 4.9,
    reviews: 4521,
    price: 18500,
    roomsAvailable: 6,
    totalRooms: 120,
    roomType: '5 Star Luxury',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Multiple Pools', 'Spa', 'Fine Dining', 'Lake View', 'Yacht Club', 'Business Center'],
    images: [
      'https://images.unsplash.com/photo-1631049307038-da31f703988f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584377860899-d2ae8d3e8d7e?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Ultra-luxury palace hotel with breathtaking lake views and world-class service',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 3700,
    discount: 0,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 6,
    isActive: true
  },
  {
    id: 'HT-012',
    name: 'Taj Lake Palace Udaipur',
    city: 'Udaipur',
    location: 'Lake Pichola, Udaipur',
    address: 'Lake Pichola, Udaipur 313001',
    rating: 4.8,
    reviews: 3876,
    price: 16500,
    roomsAvailable: 8,
    totalRooms: 83,
    roomType: '5 Star Iconic',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Spa', 'Fine Dining', 'Lake View', 'Ayurveda Center', 'Boat Rides'],
    images: [
      'https://images.unsplash.com/photo-1566669537602-b8f7b5ff87f9?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Iconic floating palace with magnificent views and heritage hospitality',
    cancellation: 'Free cancellation until 48 hours before checkin',
    taxes: 3300,
    discount: 1650,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 8,
    isActive: true
  },
  {
    id: 'HT-013',
    name: 'Radisson Blu Udaipur Palace Resort',
    city: 'Udaipur',
    location: 'Hiran Magri, Udaipur',
    address: 'Hiran Magri, Udaipur 313001',
    rating: 4.6,
    reviews: 2345,
    price: 9999,
    roomsAvailable: 14,
    totalRooms: 180,
    roomType: '5 Star Premium',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Fitness Center', 'Restaurant', 'Lake View', 'Kids Club'],
    images: [
      'https://images.unsplash.com/photo-1578821868057-c31b76b80d73?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Premium resort with luxury amenities and stunning lake views',
    cancellation: 'Free cancellation until 48 hours before checkin',
    taxes: 2000,
    discount: 1000,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 14,
    isActive: true
  },
  {
    id: 'HT-014',
    name: 'Aravali Resort Udaipur',
    city: 'Udaipur',
    location: 'Aravali Hills, Udaipur',
    address: 'Aravali Hills, Udaipur 313001',
    rating: 4.5,
    reviews: 1987,
    price: 6500,
    roomsAvailable: 22,
    totalRooms: 150,
    roomType: '4 Star Premium',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Swimming Pool', 'Spa', 'Restaurant', 'Fitness Center', 'Garden'],
    images: [
      'https://images.unsplash.com/photo-1595576142684-e58829a70f36?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Peaceful resort nestled in Aravali hills with nature views',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 1300,
    discount: 650,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 22,
    isActive: true
  },
  {
    id: 'HT-015',
    name: 'Udai Vilas Palace Hotel',
    city: 'Udaipur',
    location: 'Udai Bilas, Udaipur',
    address: 'City Palace Road, Udaipur 313001',
    rating: 4.7,
    reviews: 2654,
    price: 12500,
    roomsAvailable: 10,
    totalRooms: 100,
    roomType: '5 Star Heritage',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Palace Museum', 'Spa', 'Fine Dining', 'Heritage Tours', 'Courtyard Pool'],
    images: [
      'https://images.unsplash.com/photo-1569305817188-a1ba3a0fde2c?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Heritage palace hotel with authentic royal experience and rich history',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 2500,
    discount: 0,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 10,
    isActive: true
  },
  {
    id: 'HT-016',
    name: 'Jaiwana Haveli Udaipur',
    city: 'Udaipur',
    location: 'Old City, Udaipur',
    address: '42 Namhpol Lane, Old City, Udaipur 313001',
    rating: 4.4,
    reviews: 1543,
    price: 5200,
    roomsAvailable: 28,
    totalRooms: 170,
    roomType: '3 Star Heritage',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Rooftop Restaurant', 'City View', 'Traditional Decor', 'Balcony'],
    images: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Charming heritage haveli with traditional architecture in old city',
    cancellation: 'Free cancellation until 24 hours before checkin',
    taxes: 1040,
    discount: 520,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 28,
    isActive: true
  },
  {
    id: 'HT-017',
    name: 'Hotel Rangoli Udaipur',
    city: 'Udaipur',
    location: 'Bhattiyani Chohatta, Udaipur',
    address: 'Bhattiyani Chohatta, Udaipur 313001',
    rating: 4.2,
    reviews: 987,
    price: 3200,
    roomsAvailable: 35,
    totalRooms: 120,
    roomType: '2 Star Budget',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Budget Restaurant', 'Lounge'],
    images: [
      'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Budget-friendly hotel with basic amenities in city center',
    cancellation: 'Free cancellation until 12 hours before checkin',
    taxes: 640,
    discount: 320,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 35,
    isActive: true
  },
  {
    id: 'HT-018',
    name: 'Shiv Nivas Palace Udaipur',
    city: 'Udaipur',
    location: 'Sisarma, Udaipur',
    address: 'Sisarma Road, Udaipur 313001',
    rating: 4.6,
    reviews: 2156,
    price: 10500,
    roomsAvailable: 12,
    totalRooms: 62,
    roomType: '5 Star Boutique',
    checkinTime: '14:00',
    checkoutTime: '11:00',
    amenities: ['Free WiFi', 'Spa', 'Personalized Service', 'Lake View', 'Fine Dining'],
    images: [
      'https://images.unsplash.com/photo-1635558063341-0f4755adbc64?auto=format&fit=crop&w=800&q=80'
    ],
    description: 'Exclusive boutique palace hotel with personalized luxury experience',
    cancellation: 'Free cancellation until 48 hours before checkin',
    taxes: 2100,
    discount: 1050,
    nightsCount: 1,
    isAvailable: true,
    availableRooms: 12,
    isActive: true
  }
]

const mockBuses = [
  {
    id: 'BS-001',
    operatorName: 'Redbus Express',
    busNumber: 'RB-2401',
    departure: { city: 'Delhi (ISBT)', time: '06:00' },
    arrival: { city: 'Jaipur (Ajmeri Gate)', time: '10:30' },
    durationMinutes: 270,
    duration: '4h 30m',
    from: 'Delhi',
    to: 'Jaipur',
    distance: 280,
    price: 599,
    type: 'AC Sleeper',
    seatsAvailable: 32,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Power Outlets', 'Onboard Snacks'],
    rating: 4.3,
    reviews: 1876,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-002',
    operatorName: 'Volvo Journeys',
    busNumber: 'VJ-5601',
    departure: { city: 'Delhi (ISBT)', time: '08:00' },
    arrival: { city: 'Jaipur (Ajmeri Gate)', time: '12:30' },
    durationMinutes: 270,
    duration: '4h 30m',
    from: 'Delhi',
    to: 'Jaipur',
    distance: 280,
    price: 799,
    type: 'AC Luxury',
    seatsAvailable: 18,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Power Outlets', 'Meal', 'USB Charging'],
    rating: 4.6,
    reviews: 2543,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-003',
    operatorName: 'Sky Bus',
    busNumber: 'SB-3301',
    departure: { city: 'Delhi (ISBT)', time: '10:00' },
    arrival: { city: 'Jaipur (Ajmeri Gate)', time: '14:30' },
    durationMinutes: 270,
    duration: '4h 30m',
    from: 'Delhi',
    to: 'Jaipur',
    distance: 280,
    price: 449,
    type: 'Non-AC',
    seatsAvailable: 25,
    totalSeats: 48,
    amenities: ['WiFi', 'Snacks'],
    rating: 3.8,
    reviews: 1234,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-004',
    operatorName: 'Shatabdi Express',
    busNumber: 'SE-7701',
    departure: { city: 'Delhi (ISBT)', time: '14:00' },
    arrival: { city: 'Jaipur (Ajmeri Gate)', time: '18:30' },
    durationMinutes: 270,
    duration: '4h 30m',
    from: 'Delhi',
    to: 'Jaipur',
    distance: 280,
    price: 649,
    type: 'AC Recliner',
    seatsAvailable: 35,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Reclining Seats', 'Power Outlets'],
    rating: 4.4,
    reviews: 1654,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-005',
    operatorName: 'FirstJourney',
    busNumber: 'FJ-9901',
    departure: { city: 'Delhi (ISBT)', time: '22:00' },
    arrival: { city: 'Jaipur (Ajmeri Gate)', time: '02:30' },
    durationMinutes: 270,
    duration: '4h 30m',
    from: 'Delhi',
    to: 'Jaipur',
    distance: 280,
    price: 399,
    type: 'Non-AC Sleeper',
    seatsAvailable: 42,
    totalSeats: 48,
    amenities: ['WiFi', 'Berth'],
    rating: 3.5,
    reviews: 876,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-006',
    operatorName: 'Redbus Express',
    busNumber: 'RB-2402',
    departure: { city: 'Mumbai (Dadar)', time: '07:00' },
    arrival: { city: 'Pune (Station)', time: '11:30' },
    durationMinutes: 270,
    duration: '4h 30m',
    from: 'Mumbai',
    to: 'Pune',
    distance: 190,
    price: 499,
    type: 'AC Sleeper',
    seatsAvailable: 28,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Power Outlets'],
    rating: 4.2,
    reviews: 1432,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-007',
    operatorName: 'Volvo Journeys',
    busNumber: 'VJ-5602',
    departure: { city: 'Mumbai (Dadar)', time: '09:00' },
    arrival: { city: 'Pune (Station)', time: '13:30' },
    durationMinutes: 270,
    duration: '4h 30m',
    from: 'Mumbai',
    to: 'Pune',
    distance: 190,
    price: 699,
    type: 'AC Luxury',
    seatsAvailable: 22,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Power Outlets', 'Meal'],
    rating: 4.5,
    reviews: 1987,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-008',
    operatorName: 'Sky Bus',
    busNumber: 'SB-3302',
    departure: { city: 'Bangalore (Majestic)', time: '08:00' },
    arrival: { city: 'Hyderabad (Jubilee)', time: '15:00' },
    durationMinutes: 420,
    duration: '7h',
    from: 'Bangalore',
    to: 'Hyderabad',
    distance: 570,
    price: 599,
    type: 'AC Sleeper',
    seatsAvailable: 30,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Snacks'],
    rating: 4.0,
    reviews: 1123,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-009',
    operatorName: 'Shatabdi Express',
    busNumber: 'SE-7702',
    departure: { city: 'Bangalore (Majestic)', time: '09:30' },
    arrival: { city: 'Hyderabad (Jubilee)', time: '16:30' },
    durationMinutes: 420,
    duration: '7h',
    from: 'Bangalore',
    to: 'Hyderabad',
    distance: 570,
    price: 749,
    type: 'AC Luxury',
    seatsAvailable: 15,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Power Outlets', 'Meal', 'Extra Legroom'],
    rating: 4.7,
    reviews: 2156,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-010',
    operatorName: 'FirstJourney',
    busNumber: 'FJ-9902',
    departure: { city: 'Bangalore (Majestic)', time: '22:00' },
    arrival: { city: 'Hyderabad (Jubilee)', time: '05:00' },
    durationMinutes: 420,
    duration: '7h',
    from: 'Bangalore',
    to: 'Hyderabad',
    distance: 570,
    price: 449,
    type: 'Non-AC Sleeper',
    seatsAvailable: 38,
    totalSeats: 48,
    amenities: ['WiFi', 'Berth'],
    rating: 3.6,
    reviews: 654,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-011',
    operatorName: 'Redbus Express',
    busNumber: 'RB-2403',
    departure: { city: 'Delhi (ISBT)', time: '20:00' },
    arrival: { city: 'Mumbai (Central)', time: '08:00' },
    durationMinutes: 720,
    duration: '12h',
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    price: 899,
    type: 'AC Sleeper',
    seatsAvailable: 32,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Power Outlets', 'Meals'],
    rating: 4.2,
    reviews: 2145,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-012',
    operatorName: 'Volvo Journeys',
    busNumber: 'VJ-5603',
    departure: { city: 'Delhi (ISBT)', time: '18:30' },
    arrival: { city: 'Mumbai (Central)', time: '06:30' },
    durationMinutes: 720,
    duration: '12h',
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    price: 1199,
    type: 'AC Luxury',
    seatsAvailable: 18,
    totalSeats: 48,
    amenities: ['AC', 'WiFi', 'Power Outlets', 'Gourmet Meals', 'USB Charging'],
    rating: 4.6,
    reviews: 3421,
    listingStatus: 'APPROVED',
    isActive: true
  },
  {
    id: 'BS-013',
    operatorName: 'Sky Bus',
    busNumber: 'SB-3303',
    departure: { city: 'Delhi (ISBT)', time: '08:00' },
    arrival: { city: 'Mumbai (Central)', time: '20:00' },
    durationMinutes: 720,
    duration: '12h',
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    price: 649,
    type: 'Non-AC',
    seatsAvailable: 28,
    totalSeats: 48,
    amenities: ['WiFi', 'Snacks'],
    rating: 3.9,
    reviews: 1876,
    listingStatus: 'APPROVED',
    isActive: true
  }
]

const mockTrains = [
  {
    id: 'TR-001',
    trainName: 'Rajdhani Express',
    trainNumber: '12001',
    departure: { city: 'Delhi (NDLS)', time: '16:00', station: 'New Delhi Railway Station' },
    arrival: { city: 'Mumbai (BCT)', time: '08:00', station: 'Mumbai Central' },
    durationMinutes: 960,
    duration: '16h',
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    price: 1899,
    class: 'AC 1st Class',
    classType: 'First AC',
    seatsAvailable: 24,
    totalSeats: 72,
    type: 'Premium Express',
    amenities: ['Meals', 'Reading Light', 'Charging Point', 'Bedroll'],
    rating: 4.6,
    reviews: 2341,
    isActive: true
  },
  {
    id: 'TR-002',
    trainName: 'Rajdhani Express',
    trainNumber: '12001',
    departure: { city: 'Delhi (NDLS)', time: '16:00', station: 'New Delhi Railway Station' },
    arrival: { city: 'Mumbai (BCT)', time: '08:00', station: 'Mumbai Central' },
    durationMinutes: 960,
    duration: '16h',
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    price: 1199,
    class: 'AC 2 Tier',
    classType: 'Second AC',
    seatsAvailable: 48,
    totalSeats: 96,
    type: 'Premium Express',
    amenities: ['Meals', 'Reading Light', 'Charging Point'],
    rating: 4.4,
    reviews: 3121,
    isActive: true
  },
  {
    id: 'TR-003',
    trainName: 'Shatabdi Express',
    trainNumber: '12052',
    departure: { city: 'Delhi (NDLS)', time: '06:00', station: 'New Delhi Railway Station' },
    arrival: { city: 'Jaipur (JP)', time: '10:15', station: 'Jaipur Railway Station' },
    durationMinutes: 255,
    duration: '4h 15m',
    from: 'Delhi',
    to: 'Jaipur',
    distance: 280,
    price: 699,
    class: 'AC Chair Car',
    classType: 'Chair Car',
    seatsAvailable: 36,
    totalSeats: 84,
    type: 'Express',
    amenities: ['Breakfast', 'Charging Point', 'Seat Recline'],
    rating: 4.3,
    reviews: 1876,
    isActive: true
  },
  {
    id: 'TR-004',
    trainName: 'Intercity Express',
    trainNumber: '12023',
    departure: { city: 'Delhi (NDLS)', time: '06:30', station: 'New Delhi Railway Station' },
    arrival: { city: 'Agra (AG)', time: '09:00', station: 'Agra Cantt Railway Station' },
    durationMinutes: 150,
    duration: '2h 30m',
    from: 'Delhi',
    to: 'Agra',
    distance: 207,
    price: 399,
    class: 'AC 3 Tier',
    classType: 'Third AC',
    seatsAvailable: 52,
    totalSeats: 120,
    type: 'Intercity Express',
    amenities: ['Charging Point'],
    rating: 4.0,
    reviews: 1234,
    isActive: true
  },
  {
    id: 'TR-005',
    trainName: 'Mysore Express',
    trainNumber: '12007',
    departure: { city: 'Delhi (NDLS)', time: '20:00', station: 'New Delhi Railway Station' },
    arrival: { city: 'Bangalore (BNC)', time: '12:00', station: 'Bangalore City Railway Station' },
    durationMinutes: 1080,
    duration: '18h',
    from: 'Delhi',
    to: 'Bangalore',
    distance: 2150,
    price: 1299,
    class: 'AC 2 Tier',
    classType: 'Second AC',
    seatsAvailable: 40,
    totalSeats: 96,
    type: 'Premium Express',
    amenities: ['Meals', 'Charging Point', 'Bedroll'],
    rating: 4.5,
    reviews: 2654,
    isActive: true
  },
  {
    id: 'TR-006',
    trainName: 'Karnataka Express',
    trainNumber: '12627',
    departure: { city: 'Delhi (NDLS)', time: '19:00', station: 'New Delhi Railway Station' },
    arrival: { city: 'Bangalore (BNC)', time: '11:30', station: 'Bangalore City Railway Station' },
    durationMinutes: 1050,
    duration: '17h 30m',
    from: 'Delhi',
    to: 'Bangalore',
    distance: 2150,
    price: 999,
    class: 'AC 3 Tier',
    classType: 'Third AC',
    seatsAvailable: 58,
    totalSeats: 120,
    type: 'Express',
    amenities: ['Light Snacks', 'Charging Point'],
    rating: 4.1,
    reviews: 1987,
    isActive: true
  },
  {
    id: 'TR-007',
    trainName: 'Mumbai Rajdhani',
    trainNumber: '12953',
    departure: { city: 'Delhi (NDLS)', time: '14:50', station: 'New Delhi Railway Station' },
    arrival: { city: 'Mumbai (CSTM)', time: '08:20', station: 'Mumbai Central' },
    durationMinutes: 945,
    duration: '15h 30m',
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    price: 2099,
    class: 'AC 1st Class',
    classType: 'First AC',
    seatsAvailable: 18,
    totalSeats: 72,
    type: 'Premium Express',
    amenities: ['Premium Meals', 'Charged Breakfast', 'Exclusive Lounge'],
    rating: 4.8,
    reviews: 3456,
    isActive: true
  },
  {
    id: 'TR-008',
    trainName: 'Punjab Mail',
    trainNumber: '12015',
    departure: { city: 'Delhi (NDLS)', time: '23:00', station: 'New Delhi Railway Station' },
    arrival: { city: 'Mumbai (CSTM)', time: '14:00', station: 'Mumbai Central' },
    durationMinutes: 1020,
    duration: '17h',
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    price: 799,
    class: 'AC 3 Tier',
    classType: 'Third AC',
    seatsAvailable: 64,
    totalSeats: 120,
    type: 'Mail Express',
    amenities: ['Tea/Coffee', 'Charging Point'],
    rating: 3.9,
    reviews: 1456,
    isActive: true
  },
  {
    id: 'TR-009',
    trainName: 'Hyderabad Express',
    trainNumber: '12723',
    departure: { city: 'Bangalore (SBC)', time: '17:30', station: 'Bangalore City' },
    arrival: { city: 'Hyderabad (SC)', time: '06:15', station: 'Secunderabad' },
    durationMinutes: 720,
    duration: '12h',
    from: 'Bangalore',
    to: 'Hyderabad',
    distance: 570,
    price: 899,
    class: 'AC 2 Tier',
    classType: 'Second AC',
    seatsAvailable: 42,
    totalSeats: 96,
    type: 'Express',
    amenities: ['Dinner', 'Charging Point', 'Bedroll'],
    rating: 4.3,
    reviews: 1654,
    isActive: true
  },
  {
    id: 'TR-010',
    trainName: 'Bangalore Express',
    trainNumber: '12657',
    departure: { city: 'Hyderabad (SC)', time: '21:00', station: 'Secunderabad' },
    arrival: { city: 'Bangalore (SBC)', time: '09:00', station: 'Bangalore City' },
    durationMinutes: 720,
    duration: '12h',
    from: 'Hyderabad',
    to: 'Bangalore',
    distance: 570,
    price: 799,
    class: 'AC 3 Tier',
    classType: 'Third AC',
    seatsAvailable: 56,
    totalSeats: 120,
    type: 'Express',
    amenities: ['Snacks', 'Charging Point'],
    rating: 4.0,
    reviews: 1234,
    isActive: true
  },
  // Ahmedabad - Surat Routes
  {
    id: 'TR-011',
    trainName: 'Shatabdi Express',
    trainNumber: '19015',
    departure: { city: 'Ahmedabad Junction (ADI)', time: '06:35', station: 'Ahmedabad Junction' },
    arrival: { city: 'Surat (ST)', time: '09:15', station: 'Surat Railway Station' },
    durationMinutes: 160,
    duration: '2h 40m',
    from: 'Ahmedabad',
    to: 'Surat',
    distance: 262,
    price: 399,
    class: 'AC Chair Car',
    classType: 'Chair Car',
    seatsAvailable: 42,
    totalSeats: 84,
    type: 'Express',
    amenities: ['Breakfast', 'Charging Point', 'Seat Recline'],
    rating: 4.5,
    reviews: 1876,
    isActive: true
  },
  {
    id: 'TR-012',
    trainName: 'Gujarat Mail',
    trainNumber: '19017',
    departure: { city: 'Ahmedabad Junction (ADI)', time: '09:00', station: 'Ahmedabad Junction' },
    arrival: { city: 'Surat (ST)', time: '12:00', station: 'Surat Railway Station' },
    durationMinutes: 180,
    duration: '3h',
    from: 'Ahmedabad',
    to: 'Surat',
    distance: 262,
    price: 299,
    class: 'AC 3 Tier',
    classType: 'Third AC',
    seatsAvailable: 58,
    totalSeats: 120,
    type: 'Express',
    amenities: ['Tea/Coffee', 'Charging Point'],
    rating: 4.2,
    reviews: 1543,
    isActive: true
  },
  {
    id: 'TR-013',
    trainName: 'Surat Express',
    trainNumber: '19019',
    departure: { city: 'Ahmedabad Junction (ADI)', time: '14:30', station: 'Ahmedabad Junction' },
    arrival: { city: 'Surat (ST)', time: '17:45', station: 'Surat Railway Station' },
    durationMinutes: 195,
    duration: '3h 15m',
    from: 'Ahmedabad',
    to: 'Surat',
    distance: 262,
    price: 349,
    class: 'AC 2 Tier',
    classType: 'Second AC',
    seatsAvailable: 48,
    totalSeats: 96,
    type: 'Express',
    amenities: ['Light Snacks', 'Charging Point', 'Bedroll'],
    rating: 4.4,
    reviews: 1987,
    isActive: true
  },
  {
    id: 'TR-014',
    trainName: 'Ahmedabad - Surat Local',
    trainNumber: '19021',
    departure: { city: 'Ahmedabad Junction (ADI)', time: '18:00', station: 'Ahmedabad Junction' },
    arrival: { city: 'Surat (ST)', time: '21:15', station: 'Surat Railway Station' },
    durationMinutes: 195,
    duration: '3h 15m',
    from: 'Ahmedabad',
    to: 'Surat',
    distance: 262,
    price: 249,
    class: 'General',
    classType: 'General',
    seatsAvailable: 72,
    totalSeats: 200,
    type: 'Passenger',
    amenities: ['Fan', 'Lavatory'],
    rating: 3.8,
    reviews: 876,
    isActive: true
  },
  // Surat - Ahmedabad (Return)
  {
    id: 'TR-015',
    trainName: 'Shatabdi Express',
    trainNumber: '19016',
    departure: { city: 'Surat (ST)', time: '14:00', station: 'Surat Railway Station' },
    arrival: { city: 'Ahmedabad Junction (ADI)', time: '16:45', station: 'Ahmedabad Junction' },
    durationMinutes: 165,
    duration: '2h 45m',
    from: 'Surat',
    to: 'Ahmedabad',
    distance: 262,
    price: 399,
    class: 'AC Chair Car',
    classType: 'Chair Car',
    seatsAvailable: 38,
    totalSeats: 84,
    type: 'Express',
    amenities: ['Breakfast', 'Charging Point', 'Seat Recline'],
    rating: 4.5,
    reviews: 2001,
    isActive: true
  },
  {
    id: 'TR-016',
    trainName: 'Gujarat Express',
    trainNumber: '19018',
    departure: { city: 'Surat (ST)', time: '20:00', station: 'Surat Railway Station' },
    arrival: { city: 'Ahmedabad Junction (ADI)', time: '23:15', station: 'Ahmedabad Junction' },
    durationMinutes: 195,
    duration: '3h 15m',
    from: 'Surat',
    to: 'Ahmedabad',
    distance: 262,
    price: 349,
    class: 'AC 2 Tier',
    classType: 'Second AC',
    seatsAvailable: 52,
    totalSeats: 96,
    type: 'Express',
    amenities: ['Dinner', 'Charging Point', 'Bedroll'],
    rating: 4.3,
    reviews: 1654,
    isActive: true
  }
]

const mockCabs = [
  {
    id: 'CB-001',
    provider: 'Uber',
    carType: 'UberGo',
    seatsCapacity: 4,
    price: 250,
    baseFare: 50,
    perKmFare: 8,
    perMinFare: 2,
    from: 'Delhi',
    to: 'Noida',
    distance: 25,
    durationMinutes: 35,
    durationText: '35 mins',
    availableCars: 45,
    rating: 4.5,
    reviews: 12345,
    ac: true,
    wifi: false,
    powerBank: false,
    bottleWater: false,
    isActive: true
  },
  {
    id: 'CB-002',
    provider: 'Ola',
    carType: 'Ola Prime',
    seatsCapacity: 4,
    price: 350,
    baseFare: 50,
    perKmFare: 10,
    perMinFare: 2.5,
    from: 'Delhi',
    to: 'Noida',
    distance: 25,
    durationMinutes: 35,
    durationText: '35 mins',
    availableCars: 38,
    rating: 4.4,
    reviews: 10987,
    ac: true,
    wifi: true,
    powerBank: true,
    bottleWater: true,
    isActive: true
  },
  {
    id: 'CB-003',
    provider: 'Uber',
    carType: 'Uber Premium',
    seatsCapacity: 4,
    price: 450,
    baseFare: 75,
    perKmFare: 12,
    perMinFare: 3,
    from: 'Delhi',
    to: 'Noida',
    distance: 25,
    durationMinutes: 35,
    durationText: '35 mins',
    availableCars: 22,
    rating: 4.7,
    reviews: 8765,
    ac: true,
    wifi: true,
    powerBank: true,
    bottleWater: true,
    isActive: true
  },
  {
    id: 'CB-004',
    provider: 'Ola',
    carType: 'Ola XL',
    seatsCapacity: 6,
    price: 320,
    baseFare: 50,
    perKmFare: 9,
    perMinFare: 2,
    from: 'Delhi',
    to: 'Noida',
    distance: 25,
    durationMinutes: 35,
    durationText: '35 mins',
    availableCars: 15,
    rating: 4.3,
    reviews: 7654,
    ac: true,
    wifi: false,
    powerBank: false,
    bottleWater: false,
    isActive: true
  },
  {
    id: 'CB-005',
    provider: 'Uber',
    carType: 'Uber XL',
    seatsCapacity: 6,
    price: 380,
    baseFare: 60,
    perKmFare: 10,
    perMinFare: 2.5,
    from: 'Delhi',
    to: 'Noida',
    distance: 25,
    durationMinutes: 35,
    durationText: '35 mins',
    availableCars: 28,
    rating: 4.6,
    reviews: 9876,
    ac: true,
    wifi: true,
    powerBank: true,
    bottleWater: true,
    isActive: true
  },
  {
    id: 'CB-006',
    provider: 'Rapido',
    carType: 'Auto',
    seatsCapacity: 3,
    price: 150,
    baseFare: 30,
    perKmFare: 5,
    perMinFare: 1,
    from: 'Delhi',
    to: 'Noida',
    distance: 25,
    durationMinutes: 40,
    durationText: '40 mins',
    availableCars: 60,
    rating: 4.1,
    reviews: 6543,
    ac: false,
    wifi: false,
    powerBank: false,
    bottleWater: false,
    isActive: true
  },
  {
    id: 'CB-007',
    provider: 'Uber',
    carType: 'UberGo',
    seatsCapacity: 4,
    price: 280,
    baseFare: 50,
    perKmFare: 8,
    perMinFare: 2,
    from: 'Mumbai',
    to: 'Pune',
    distance: 150,
    durationMinutes: 180,
    durationText: '3 hours',
    availableCars: 32,
    rating: 4.5,
    reviews: 11234,
    ac: true,
    wifi: false,
    powerBank: false,
    bottleWater: false,
    isActive: true
  },
  {
    id: 'CB-008',
    provider: 'Ola',
    carType: 'Ola Prime',
    seatsCapacity: 4,
    price: 380,
    baseFare: 75,
    perKmFare: 10,
    perMinFare: 2.5,
    from: 'Mumbai',
    to: 'Pune',
    distance: 150,
    durationMinutes: 180,
    durationText: '3 hours',
    availableCars: 25,
    rating: 4.6,
    reviews: 10456,
    ac: true,
    wifi: true,
    powerBank: true,
    bottleWater: true,
    isActive: true
  },
  {
    id: 'CB-009',
    provider: 'Uber',
    carType: 'Uber Premium',
    seatsCapacity: 4,
    price: 520,
    baseFare: 100,
    perKmFare: 15,
    perMinFare: 3.5,
    from: 'Mumbai',
    to: 'Pune',
    distance: 150,
    durationMinutes: 180,
    durationText: '3 hours',
    availableCars: 18,
    rating: 4.8,
    reviews: 9123,
    ac: true,
    wifi: true,
    powerBank: true,
    bottleWater: true,
    isActive: true
  },
  {
    id: 'CB-010',
    provider: 'Ola',
    carType: 'Ola XL',
    seatsCapacity: 6,
    price: 420,
    baseFare: 75,
    perKmFare: 12,
    perMinFare: 2.5,
    from: 'Mumbai',
    to: 'Pune',
    distance: 150,
    durationMinutes: 180,
    durationText: '3 hours',
    availableCars: 12,
    rating: 4.4,
    reviews: 8234,
    ac: true,
    wifi: false,
    powerBank: false,
    bottleWater: false,
    isActive: true
  },
  {
    id: 'CB-011',
    provider: 'Uber',
    carType: 'UberGo',
    seatsCapacity: 4,
    price: 1850,
    baseFare: 100,
    perKmFare: 8,
    perMinFare: 1.5,
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    durationMinutes: 1320,
    durationText: '22 hours',
    availableCars: 28,
    rating: 4.6,
    reviews: 15430,
    ac: true,
    wifi: true,
    powerBank: true,
    bottleWater: true,
    isActive: true
  },
  {
    id: 'CB-012',
    provider: 'Ola',
    carType: 'Ola Prime',
    seatsCapacity: 4,
    price: 2100,
    baseFare: 120,
    perKmFare: 9,
    perMinFare: 2,
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    durationMinutes: 1320,
    durationText: '22 hours',
    availableCars: 22,
    rating: 4.7,
    reviews: 14500,
    ac: true,
    wifi: true,
    powerBank: true,
    bottleWater: true,
    isActive: true
  },
  {
    id: 'CB-013',
    provider: 'Rapido',
    carType: 'Auto Express',
    seatsCapacity: 3,
    price: 1500,
    baseFare: 80,
    perKmFare: 7,
    perMinFare: 1,
    from: 'Delhi',
    to: 'Mumbai',
    distance: 1440,
    durationMinutes: 1440,
    durationText: '24 hours',
    availableCars: 35,
    rating: 4.2,
    reviews: 9876,
    ac: false,
    wifi: false,
    powerBank: false,
    bottleWater: true,
    isActive: true
  }
]

// Extra test data for comprehensive testing
mockHotels.push(
  // Jaipur Hotels
  { id: 'HT-TEST-001', name: 'Rambagh Palace Jaipur', city: 'Jaipur', location: 'Jaipur', address: 'Jaipur', rating: 4.8, reviews: 2100, price: 8500, roomsAvailable: 15, totalRooms: 100, amenities: ['WiFi', 'Pool', 'Spa'], description: 'Luxury palace hotel', isActive: true, images: ['https://images.unsplash.com/photo-1631049307038-da31f703988f?auto=format&fit=crop&w=800&q=80'], taxes: 1700, discount: 0, nightsCount: 1, isAvailable: true, availableRooms: 15 },
  { id: 'HT-TEST-002', name: 'Jaipur Marriott', city: 'Jaipur', location: 'Jaipur', address: 'Jaipur', rating: 4.5, reviews: 1543, price: 5500, roomsAvailable: 25, totalRooms: 200, amenities: ['WiFi', 'Pool'], description: 'Premium hotel', isActive: true, images: ['https://images.unsplash.com/photo-1578821868057-c31b76b80d73?auto=format&fit=crop&w=800&q=80'], taxes: 1100, discount: 550, nightsCount: 1, isAvailable: true, availableRooms: 25 },

  // Agra Hotels
  { id: 'HT-TEST-003', name: 'Taj View Hotel Agra', city: 'Agra', location: 'Agra', address: 'Agra', rating: 4.7, reviews: 1876, price: 6200, roomsAvailable: 18, totalRooms: 120, amenities: ['WiFi', 'Restaurant'], description: 'Taj view hotel', isActive: true, images: ['https://images.unsplash.com/photo-1566669537602-b8f7b5ff87f9?auto=format&fit=crop&w=800&q=80'], taxes: 1240, discount: 620, nightsCount: 1, isAvailable: true, availableRooms: 18 },
  { id: 'HT-TEST-004', name: 'Agra Grand Hotel', city: 'Agra', location: 'Agra', address: 'Agra', rating: 4.3, reviews: 987, price: 3500, roomsAvailable: 30, totalRooms: 150, amenities: ['WiFi'], description: 'Budget hotel', isActive: true, images: ['https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=800&q=80'], taxes: 700, discount: 350, nightsCount: 1, isAvailable: true, availableRooms: 30 },

  // Goa Hotels
  { id: 'HT-TEST-005', name: 'Taj Exotica Goa', city: 'Goa', location: 'Goa', address: 'Goa', rating: 4.8, reviews: 2345, price: 9500, roomsAvailable: 12, totalRooms: 80, amenities: ['WiFi', 'Pool', 'Beach'], description: 'Luxury beach resort', isActive: true, images: ['https://images.unsplash.com/photo-1595576142684-e58829a70f36?auto=format&fit=crop&w=800&q=80'], taxes: 1900, discount: 0, nightsCount: 1, isAvailable: true, availableRooms: 12 },
  { id: 'HT-TEST-006', name: 'Goa Beach Resort', city: 'Goa', location: 'Goa', address: 'Goa', rating: 4.4, reviews: 1432, price: 4800, roomsAvailable: 22, totalRooms: 140, amenities: ['WiFi', 'Beach'], description: 'Beach resort', isActive: true, images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b8d5?auto=format&fit=crop&w=800&q=80'], taxes: 960, discount: 480, nightsCount: 1, isAvailable: true, availableRooms: 22 },

  // Hyderabad Hotels
  { id: 'HT-TEST-007', name: 'Hyatt House Hyderabad', city: 'Hyderabad', location: 'Hyderabad', address: 'Hyderabad', rating: 4.6, reviews: 1654, price: 5999, roomsAvailable: 20, totalRooms: 180, amenities: ['WiFi', 'Pool'], description: 'Premium hotel', isActive: true, images: ['https://images.unsplash.com/photo-1564376264095-8d6e20a1c7f7?auto=format&fit=crop&w=800&q=80'], taxes: 1200, discount: 600, nightsCount: 1, isAvailable: true, availableRooms: 20 },

  // Kolkata Hotels
  { id: 'HT-TEST-008', name: 'Kolkata Heritage Hotel', city: 'Kolkata', location: 'Kolkata', address: 'Kolkata', rating: 4.5, reviews: 1234, price: 4200, roomsAvailable: 28, totalRooms: 160, amenities: ['WiFi'], description: 'Heritage hotel', isActive: true, images: ['https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=800&q=80'], taxes: 840, discount: 420, nightsCount: 1, isAvailable: true, availableRooms: 28 },

  // Pune Hotels
  { id: 'HT-TEST-009', name: 'Pune City Hotel', city: 'Pune', location: 'Pune', address: 'Pune', rating: 4.4, reviews: 1876, price: 3800, roomsAvailable: 35, totalRooms: 200, amenities: ['WiFi'], description: 'City hotel', isActive: true, images: ['https://images.unsplash.com/photo-1635558063341-0f4755adbc64?auto=format&fit=crop&w=800&q=80'], taxes: 760, discount: 380, nightsCount: 1, isAvailable: true, availableRooms: 35 },

  // Srinagar Hotels
  { id: 'HT-TEST-010', name: 'Srinagar Palace Hotel', city: 'Srinagar', location: 'Srinagar', address: 'Srinagar', rating: 4.7, reviews: 2154, price: 7200, roomsAvailable: 16, totalRooms: 100, amenities: ['WiFi', 'Lake View'], description: 'Lake view hotel', isActive: true, images: ['https://images.unsplash.com/photo-1569305817188-a1ba3a0fde2c?auto=format&fit=crop&w=800&q=80'], taxes: 1440, discount: 720, nightsCount: 1, isAvailable: true, availableRooms: 16 }
)

export default {
  flights: mockFlights,
  hotels: mockHotels,
  buses: mockBuses,
  trains: mockTrains,
  cabs: mockCabs
}
