#!/bin/bash

# Color replacement script for JSX files

find src/components src/pages -name "*.jsx" -type f | while read file; do
  # Main colors
  sed -i 's/#f1f5f9/hsl(var(--b2))/g' "$file"
  sed -i 's/#06b6d4/hsl(var(--in))/g' "$file"
  sed -i 's/#ec4899/hsl(var(--a))/g' "$file"
  sed -i 's/#9ca3af/hsl(var(--bc) \/ 0.5)/g' "$file"
  sed -i 's/#374151/hsl(var(--bc) \/ 0.65)/g' "$file"
  sed -i 's/#f59e0b/hsl(var(--wa))/g' "$file"
  sed -i 's/#991b1b/hsl(var(--er) \/ 0.7)/g' "$file"
  sed -i 's/#94a3b8/hsl(var(--bc) \/ 0.5)/g' "$file"
  sed -i 's/#3b82f6/hsl(var(--p))/g' "$file"
  sed -i 's/#059669/hsl(var(--su))/g' "$file"
  sed -i 's/#fbbf24/hsl(var(--wa))/g' "$file"
  sed -i 's/#cfe4f0/hsl(var(--p) \/ 0.15)/g' "$file"
  sed -i 's/#a3c7da/hsl(var(--p) \/ 0.25)/g' "$file"
  sed -i 's/#4f46e5/hsl(var(--p))/g' "$file"
  sed -i 's/#0284c7/hsl(var(--p))/g' "$file"
  sed -i 's/#008cff/hsl(var(--p))/g' "$file"
  sed -i 's/#fee2e2/hsl(var(--er) \/ 0.08)/g' "$file"
  sed -i 's/#38bdf8/hsl(var(--p))/g' "$file"
  sed -i 's/#334155/hsl(var(--bc) \/ 0.6)/g' "$file"
  sed -i 's/#1e40af/hsl(var(--p))/g' "$file"
  sed -i 's/#003580/hsl(var(--p))/g' "$file"
  sed -i 's/#eef2ff/hsl(var(--p) \/ 0.06)/g' "$file"
  sed -i 's/#eb2226/hsl(var(--er))/g' "$file"
  sed -i 's/#fbb52c/hsl(var(--wa))/g' "$file"
  sed -i 's/#dcfce7/hsl(var(--su) \/ 0.08)/g' "$file"
  sed -i 's/#dbeac8/hsl(var(--su) \/ 0.12)/g' "$file"
  sed -i 's/#2e7d32/hsl(var(--su))/g' "$file"
  sed -i 's/#15803d/hsl(var(--su))/g' "$file"
  sed -i 's/#0A8043/hsl(var(--su))/g' "$file"
  sed -i 's/#0369a1/hsl(var(--p))/g' "$file"
  sed -i 's/#0084ff/hsl(var(--p))/g' "$file"
  sed -i 's/#1e293b/hsl(var(--bc) \/ 0.6)/g' "$file"
  sed -i 's/#ff006e/hsl(var(--a))/g' "$file"
  sed -i 's/#f43f5e/hsl(var(--er))/g' "$file"
  sed -i 's/#e63946/hsl(var(--er))/g' "$file"
  sed -i 's/#ff9e2c/hsl(var(--wa))/g' "$file"
  sed -i 's/#ffee00/hsl(var(--wa))/g' "$file"
  sed -i 's/#00ffff/hsl(var(--in))/g' "$file"
  sed -i 's/#ffff00/hsl(var(--wa))/g' "$file"
  sed -i 's/#ff00ff/hsl(var(--a))/g' "$file"
  sed -i 's/#00ff00/hsl(var(--su))/g' "$file"
  sed -i 's/#ff007f/hsl(var(--a))/g' "$file"
  sed -i 's/#febd69/hsl(var(--wa) \/ 0.6)/g' "$file"
  sed -i 's/#fca5a5/hsl(var(--er) \/ 0.4)/g' "$file"
  sed -i 's/#f0f0f0/hsl(var(--b2))/g' "$file"
  sed -i 's/#efece4/hsl(var(--b2))/g' "$file"
  sed -i 's/#eaf3df/hsl(var(--su) \/ 0.08)/g' "$file"
  sed -i 's/#e6e1d8/hsl(var(--b3))/g' "$file"
  sed -i 's/#c7d2fe/hsl(var(--p) \/ 0.2)/g' "$file"
  sed -i 's/#c0c0c0/hsl(var(--bc) \/ 0.45)/g' "$file"
  sed -i 's/#93c5fd/hsl(var(--p) \/ 0.3)/g' "$file"
  sed -i 's/#8b5cf6/hsl(var(--a))/g' "$file"
  sed -i 's/#7a8c98/hsl(var(--bc) \/ 0.55)/g' "$file"
  sed -i 's/#6366f1/hsl(var(--p))/g' "$file"
  sed -i 's/#34d399/hsl(var(--su))/g' "$file"
  sed -i 's/#16a34a/hsl(var(--su))/g' "$file"
  sed -i 's/#0ea5e9/hsl(var(--p))/g' "$file"
  sed -i 's/#0a1118/hsl(var(--bc))/g' "$file"
  sed -i 's/#fffbfb/hsl(var(--b1) \/ 0.98)/g' "$file"
  sed -i 's/#fff9db/hsl(var(--wa) \/ 0.08)/g' "$file"
  sed -i 's/#fff3cd/hsl(var(--wa) \/ 0.1)/g' "$file"
  sed -i 's/#ffe3e3/hsl(var(--er) \/ 0.12)/g' "$file"
  sed -i 's/#ffc878/hsl(var(--wa) \/ 0.6)/g' "$file"
  sed -i 's/#ffc107/hsl(var(--wa))/g' "$file"
  sed -i 's/#ffc0cb/hsl(var(--a) \/ 0.3)/g' "$file"
  sed -i 's/#ff79c6/hsl(var(--a))/g' "$file"
  sed -i 's/#fef9c3/hsl(var(--wa) \/ 0.15)/g' "$file"
  sed -i 's/#fef08a/hsl(var(--wa) \/ 0.25)/g' "$file"
  sed -i 's/#fdf5f7/hsl(var(--a) \/ 0.08)/g' "$file"
  sed -i 's/#faf7f5/hsl(var(--b2))/g' "$file"
  sed -i 's/#f9f5ff/hsl(var(--a) \/ 0.08)/g' "$file"
  sed -i 's/#f8f9fa/hsl(var(--b2))/g' "$file"
  sed -i 's/#f8f4f0/hsl(var(--b2))/g' "$file"
  sed -i 's/#f5f1e7/hsl(var(--b2))/g' "$file"
  sed -i 's/#f5a5c9/hsl(var(--a) \/ 0.4)/g' "$file"
  sed -i 's/#f4f6f8/hsl(var(--b2))/g' "$file"
  sed -i 's/#f4efe2/hsl(var(--b2))/g' "$file"
  sed -i 's/#f472b6/hsl(var(--a))/g' "$file"
  sed -i 's/#f471b6/hsl(var(--a))/g' "$file"
  sed -i 's/#f3a847/hsl(var(--wa))/g' "$file"
  sed -i 's/#f2f4f1/hsl(var(--b2))/g' "$file"
  sed -i 's/#f2f2f2/hsl(var(--b2))/g' "$file"
  sed -i 's/#f1dcc3/hsl(var(--b2))/g' "$file"
  sed -i 's/#f1c40f/hsl(var(--wa))/g' "$file"
  sed -i 's/#f0f3f6/hsl(var(--b2))/g' "$file"
  sed -i 's/#efeae6/hsl(var(--b2))/g' "$file"
  sed -i 's/#ef9995/hsl(var(--er) \/ 0.35)/g' "$file"
  sed -i 's/#ece3ca/hsl(var(--b2))/g' "$file"
  sed -i 's/#eab308/hsl(var(--wa))/g' "$file"
  sed -i 's/#ea580c/hsl(var(--wa))/g' "$file"
  sed -i 's/#e96d7b/hsl(var(--er) \/ 0.5)/g' "$file"
  sed -i 's/#e8f5e9/hsl(var(--su) \/ 0.1)/g' "$file"
  sed -i 's/#e0f2fe/hsl(var(--p) \/ 0.08)/g' "$file"
  sed -i 's/#e0a82e/hsl(var(--wa))/g' "$file"
  sed -i 's/#dc2626/hsl(var(--er))/g' "$file"
  sed -i 's/#dbeafe/hsl(var(--p) \/ 0.1)/g' "$file"
  sed -i 's/#d97706/hsl(var(--wa))/g' "$file"
  sed -i 's/#d946ef/hsl(var(--a))/g' "$file"
  sed -i 's/#d4a574/hsl(var(--wa) \/ 0.5)/g' "$file"
  sed -i 's/#d32f2f/hsl(var(--er))/g' "$file"
  sed -i 's/#c62828/hsl(var(--er) \/ 0.8)/g' "$file"
  sed -i 's/#c5a880/hsl(var(--wa) \/ 0.55)/g' "$file"
  sed -i 's/#c471ed/hsl(var(--a))/g' "$file"
  sed -i 's/#bae6fd/hsl(var(--p) \/ 0.15)/g' "$file"
  sed -i 's/#b91c1c/hsl(var(--er))/g' "$file"
  sed -i 's/#b05a00/hsl(var(--wa) \/ 0.65)/g' "$file"
  sed -i 's/#a89968/hsl(var(--wa) \/ 0.5)/g' "$file"
  sed -i 's/#a78bfa/hsl(var(--a) \/ 0.6)/g' "$file"
  sed -i 's/#92400e/hsl(var(--wa) \/ 0.7)/g' "$file"
  sed -i 's/#8fbcbb/hsl(var(--su) \/ 0.4)/g' "$file"
  sed -i 's/#8be9fd/hsl(var(--in) \/ 0.5)/g' "$file"
  sed -i 's/#8b5fbf/hsl(var(--a))/g' "$file"
  sed -i 's/#88c0d0/hsl(var(--in))/g' "$file"
  sed -i 's/#86efac/hsl(var(--su) \/ 0.6)/g' "$file"
  sed -i 's/#856404/hsl(var(--wa) \/ 0.6)/g' "$file"
  sed -i 's/#854d0e/hsl(var(--wa) \/ 0.65)/g' "$file"
  sed -i 's/#81a1c1/hsl(var(--p) \/ 0.3)/g' "$file"
  sed -i 's/#7dd3fc/hsl(var(--p) \/ 0.35)/g' "$file"
  sed -i 's/#7c3aed/hsl(var(--a))/g' "$file"
  sed -i 's/#78350f/hsl(var(--wa) \/ 0.8)/g' "$file"
  sed -i 's/#6f4e37/hsl(var(--wa) \/ 0.5)/g' "$file"
  sed -i 's/#66cc8a/hsl(var(--su))/g' "$file"
  sed -i 's/#65c3c8/hsl(var(--in))/g' "$file"
  sed -i 's/#60a5fa/hsl(var(--p) \/ 0.5)/g' "$file"
  sed -i 's/#5c33b3/hsl(var(--a))/g' "$file"
  sed -i 's/#50fa7b/hsl(var(--su))/g' "$file"
  sed -i 's/#4b6bfb/hsl(var(--p))/g' "$file"
  sed -i 's/#404040/hsl(var(--bc) \/ 0.7)/g' "$file"
  sed -i 's/#3a2d29/hsl(var(--bc))/g' "$file"
  sed -i 's/#2e3440/hsl(var(--bc))/g' "$file"
  sed -i 's/#2a303c/hsl(var(--bc) \/ 0.7)/g' "$file"
  sed -i 's/#282a36/hsl(var(--bc))/g' "$file"
  sed -i 's/#2563eb/hsl(var(--p))/g' "$file"
  sed -i 's/#22d3ee/hsl(var(--in))/g' "$file"
  sed -i 's/#1f6db8/hsl(var(--p))/g' "$file"
  sed -i 's/#1f2937/hsl(var(--bc))/g' "$file"
  sed -i 's/#1f1d1b/hsl(var(--bc))/g' "$file"
  sed -i 's/#1eb854/hsl(var(--su))/g' "$file"
  sed -i 's/#1e3a8a/hsl(var(--p) \/ 0.8)/g' "$file"
  sed -i 's/#1d4ed8/hsl(var(--p))/g' "$file"
  sed -i 's/#1c2b3d/hsl(var(--bc) \/ 0.7)/g' "$file"
  sed -i 's/#1c1415/hsl(var(--bc))/g' "$file"
  sed -i 's/#1a73e8/hsl(var(--p))/g' "$file"
  sed -i 's/#1a2e40/hsl(var(--bc))/g' "$file"
  sed -i 's/#1a1f36/hsl(var(--bc) \/ 0.8)/g' "$file"
  sed -i 's/#1a103c/hsl(var(--a) \/ 0.8)/g' "$file"
  sed -i 's/#171212/hsl(var(--bc))/g' "$file"
  sed -i 's/#120c18/hsl(var(--a) \/ 0.9)/g' "$file"
  sed -i 's/#0db981/hsl(var(--su))/g' "$file"
  sed -i 's/#09ecf3/hsl(var(--in))/g' "$file"
  sed -i 's/#09090b/hsl(var(--bc))/g' "$file"
  sed -i 's/#00d4d4/hsl(var(--in))/g' "$file"
  sed -i 's/#fffbeb/hsl(var(--wa) \/ 0.08)/g' "$file"
done

echo "✓ JSX color replacement complete"
